# Generated by Django 2.1.7 on 2019-03-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=64)),
                ('Feriado', models.CharField(max_length=64)),
                ('Data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AgendaPrivada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=64)),
                ('Compromisso', models.TextField()),
                ('Data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AgendaPublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=64)),
                ('Compromisso', models.TextField()),
                ('Data', models.DateTimeField()),
            ],
        ),
    ]
