# Generated by Django 2.1.7 on 2019-03-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendainstitucional',
            options={'verbose_name': 'Agenda Institucional', 'verbose_name_plural': 'Agenda Institucional'},
        ),
        migrations.AlterModelOptions(
            name='agendaprivada',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
        migrations.AlterModelOptions(
            name='agendapublica',
            options={'verbose_name': 'Agenda Pública', 'verbose_name_plural': 'Agenda Pública'},
        ),
        migrations.AlterField(
            model_name='agendainstitucional',
            name='Feriado',
            field=models.CharField(max_length=64, verbose_name='Nome do feriado'),
        ),
        migrations.AlterField(
            model_name='agendainstitucional',
            name='Nome',
            field=models.CharField(max_length=64, verbose_name='Nome Médico'),
        ),
        migrations.AlterField(
            model_name='agendaprivada',
            name='Compromisso',
            field=models.TextField(max_length=128, verbose_name='Tipo de compromisso'),
        ),
        migrations.AlterField(
            model_name='agendaprivada',
            name='Nome',
            field=models.CharField(max_length=64, verbose_name='Nome do médico'),
        ),
        migrations.AlterField(
            model_name='agendapublica',
            name='Compromisso',
            field=models.TextField(max_length=128, verbose_name='Tipo de compromisso'),
        ),
        migrations.AlterField(
            model_name='agendapublica',
            name='Nome',
            field=models.CharField(max_length=64, verbose_name='Nome do Médico'),
        ),
    ]
